import fs from 'node:fs';
for(const file of ['data/state.json','data/latest.json']) JSON.parse(fs.readFileSync(file,'utf8'));
const html=fs.readFileSync('public/index.html','utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)?.[1];
if(!script)throw Error('Page script missing');
new Function(script);
if(!html.includes('raw.githubusercontent.com/zdongdong8219-jpg/football-monitor/main/data/'))throw Error('Data integration missing');
if(!html.includes('强烈建议 · 2.50–2.79倍'))throw Error('Strong recommendation column missing');
if(!html.includes('predictedScore'))throw Error('Score prediction rendering missing');
if(!html.includes('combinationCount'))throw Error('Combination structure rendering missing');
if(!html.includes("market('半全场'"))throw Error('Half-full-time market rendering missing');
if(!html.includes('halfTimePrediction')||!html.includes('upgradeFrom')||!html.includes('selectionReason'))throw Error('Half-full-time rationale rendering missing');
if(!html.includes('掏空主任的裤衩子'))throw Error('Requested page title missing');
if(!html.includes('renderScanTable')||!html.includes('confidenceStars'))throw Error('Scan summary table missing');
if(!html.includes('copyScanTable')||!html.includes('ClipboardItem')||!html.includes('image/png'))throw Error('Mobile scan image copy control missing');
console.log('Football mobile build verified');
